name: Always pass 
on: [pull_request]
jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Wait 10 seconds, then pass"
      - run: sleep 10
      - run: echo "Finished waiting, exiting..."
      - run: exit 0
